### ISSUE TITLE
Can't remotely interact with Rstudio GUI over VNC

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/PoonLab#47]
```
Qt: XKEYBOARD extension not present on the X server.
Xlib:  extension "GLX" missing on display ":1".
Xlib:  extension "GLX" missing on display ":1".
Xlib:  extension "GLX" missing on display ":1".
Xlib:  extension "GLX" missing on display ":1".
Could not initialize OpenGL for RasterGLSurface, reverting to RasterSurface.
qt_xcb_createCursorXRender: query_pict_formats failed
Segmentation fault (core dumped)
art@Langley:~$ 
```

**Comment by 0ldM4j0r** [comment]
From this [thread](https://support.rstudio.com/hc/en-us/community/posts/200786228-rstudio-crashes-over-VNC-x2go) it looks like this is a common issue with rstudio. The last comment in that thread suggests that using TigerVNC instead of the default VNC should solve the problem but I haven't tested that.

A quick fix would be installing [XQuartz](https://www.xquartz.org/) and running rstudio using the command: `rstudio&` after sshing into the host with: `ssh -X username@host`.

**Comment by ArtPoon** [comment]
No longer using the Mac Pro
